/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordRouteImport } from './routes/record'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiStudyKitRouteImport } from './routes/api/study-kit'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiYoutubeRouteImport } from './routes/api/youtube'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyKitRoute = ApiStudyKitRouteImport.update({
  id: '/api/study-kit',
  path: '/api/study-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeRoute = ApiYoutubeRouteImport.update({
  id: '/api/youtube',
  path: '/api/youtube',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/youtube': typeof YoutubeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/study-kit': typeof ApiStudyKitRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/youtube': typeof ApiYoutubeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/youtube': typeof YoutubeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/study-kit': typeof ApiStudyKitRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/youtube': typeof ApiYoutubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/chat': typeof ChatRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/youtube': typeof YoutubeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/study-kit': typeof ApiStudyKitRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/youtube': typeof ApiYoutubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/notes'
    | '/profile'
    | '/record'
    | '/settings'
    | '/signup'
    | '/youtube'
    | '/api/chat'
    | '/api/study-kit'
    | '/api/transcribe'
    | '/api/youtube'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/notes'
    | '/profile'
    | '/record'
    | '/settings'
    | '/signup'
    | '/youtube'
    | '/api/chat'
    | '/api/study-kit'
    | '/api/transcribe'
    | '/api/youtube'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bookmarks'
    | '/chat'
    | '/dashboard'
    | '/login'
    | '/notes'
    | '/profile'
    | '/record'
    | '/settings'
    | '/signup'
    | '/youtube'
    | '/api/chat'
    | '/api/study-kit'
    | '/api/transcribe'
    | '/api/youtube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookmarksRoute: typeof BookmarksRoute
  ChatRoute: typeof ChatRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  ProfileRoute: typeof ProfileRoute
  RecordRoute: typeof RecordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  YoutubeRoute: typeof YoutubeRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiStudyKitRoute: typeof ApiStudyKitRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiYoutubeRoute: typeof ApiYoutubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study-kit': {
      id: '/api/study-kit'
      path: '/api/study-kit'
      fullPath: '/api/study-kit'
      preLoaderRoute: typeof ApiStudyKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube': {
      id: '/api/youtube'
      path: '/api/youtube'
      fullPath: '/api/youtube'
      preLoaderRoute: typeof ApiYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookmarksRoute: BookmarksRoute,
  ChatRoute: ChatRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  ProfileRoute: ProfileRoute,
  RecordRoute: RecordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  YoutubeRoute: YoutubeRoute,
  ApiChatRoute: ApiChatRoute,
  ApiStudyKitRoute: ApiStudyKitRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiYoutubeRoute: ApiYoutubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
