/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordRouteImport } from './routes/record'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudyPacksRouteImport } from './routes/study-packs'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as YoutubeRouteImport } from './routes/youtube'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiStudyKitRouteImport } from './routes/api/study-kit'
import { Route as ApiStudyPackRouteImport } from './routes/api/study-pack'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiYoutubeRouteImport } from './routes/api/youtube'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatChatIdRouteImport } from './routes/chat.$chatId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyPacksRoute = StudyPacksRouteImport.update({
  id: '/study-packs',
  path: '/study-packs',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeRoute = YoutubeRouteImport.update({
  id: '/youtube',
  path: '/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyKitRoute = ApiStudyKitRouteImport.update({
  id: '/api/study-kit',
  path: '/api/study-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyPackRoute = ApiStudyPackRouteImport.update({
  id: '/api/study-pack',
  path: '/api/study-pack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeRoute = ApiYoutubeRouteImport.update({
  id: '/api/youtube',
  path: '/api/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/chat': typeof ChatRouteWithChildren
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/study-packs': typeof StudyPacksRoute
  '/teacher': typeof TeacherRoute
  '/youtube': typeof YoutubeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/study-kit': typeof ApiStudyKitRoute
  '/api/study-pack': typeof ApiStudyPackRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/youtube': typeof ApiYoutubeRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/study-packs': typeof StudyPacksRoute
  '/teacher': typeof TeacherRoute
  '/youtube': typeof YoutubeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/study-kit': typeof ApiStudyKitRoute
  '/api/study-pack': typeof ApiStudyPackRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/youtube': typeof ApiYoutubeRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/chat': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bookmarks': typeof BookmarksRoute
  '/chat': typeof ChatRouteWithChildren
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/notes': typeof NotesRoute
  '/profile': typeof ProfileRoute
  '/record': typeof RecordRoute
  '/sessions': typeof SessionsRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/study-packs': typeof StudyPacksRoute
  '/teacher': typeof TeacherRoute
  '/youtube': typeof YoutubeRoute
  '/api/chat': typeof ApiChatRoute
  '/api/study-kit': typeof ApiStudyKitRoute
  '/api/study-pack': typeof ApiStudyPackRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/youtube': typeof ApiYoutubeRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/chat'
    | '/credits'
    | '/dashboard'
    | '/login'
    | '/notes'
    | '/profile'
    | '/record'
    | '/sessions'
    | '/settings'
    | '/signup'
    | '/study-packs'
    | '/teacher'
    | '/youtube'
    | '/api/chat'
    | '/api/study-kit'
    | '/api/study-pack'
    | '/api/transcribe'
    | '/api/youtube'
    | '/chat/$chatId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bookmarks'
    | '/credits'
    | '/dashboard'
    | '/login'
    | '/notes'
    | '/profile'
    | '/record'
    | '/sessions'
    | '/settings'
    | '/signup'
    | '/study-packs'
    | '/teacher'
    | '/youtube'
    | '/api/chat'
    | '/api/study-kit'
    | '/api/study-pack'
    | '/api/transcribe'
    | '/api/youtube'
    | '/chat/$chatId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bookmarks'
    | '/chat'
    | '/credits'
    | '/dashboard'
    | '/login'
    | '/notes'
    | '/profile'
    | '/record'
    | '/sessions'
    | '/settings'
    | '/signup'
    | '/study-packs'
    | '/teacher'
    | '/youtube'
    | '/api/chat'
    | '/api/study-kit'
    | '/api/study-pack'
    | '/api/transcribe'
    | '/api/youtube'
    | '/chat/$chatId'
    | '/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookmarksRoute: typeof BookmarksRoute
  ChatRoute: typeof ChatRouteWithChildren
  CreditsRoute: typeof CreditsRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  NotesRoute: typeof NotesRoute
  ProfileRoute: typeof ProfileRoute
  RecordRoute: typeof RecordRoute
  SessionsRoute: typeof SessionsRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StudyPacksRoute: typeof StudyPacksRoute
  TeacherRoute: typeof TeacherRoute
  YoutubeRoute: typeof YoutubeRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiStudyKitRoute: typeof ApiStudyKitRoute
  ApiStudyPackRoute: typeof ApiStudyPackRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiYoutubeRoute: typeof ApiYoutubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-packs': {
      id: '/study-packs'
      path: '/study-packs'
      fullPath: '/study-packs'
      preLoaderRoute: typeof StudyPacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube': {
      id: '/youtube'
      path: '/youtube'
      fullPath: '/youtube'
      preLoaderRoute: typeof YoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study-kit': {
      id: '/api/study-kit'
      path: '/api/study-kit'
      fullPath: '/api/study-kit'
      preLoaderRoute: typeof ApiStudyKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study-pack': {
      id: '/api/study-pack'
      path: '/api/study-pack'
      fullPath: '/api/study-pack'
      preLoaderRoute: typeof ApiStudyPackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube': {
      id: '/api/youtube'
      path: '/api/youtube'
      fullPath: '/api/youtube'
      preLoaderRoute: typeof ApiYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatChatIdRoute: typeof ChatChatIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatChatIdRoute: ChatChatIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookmarksRoute: BookmarksRoute,
  ChatRoute: ChatRouteWithChildren,
  CreditsRoute: CreditsRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  NotesRoute: NotesRoute,
  ProfileRoute: ProfileRoute,
  RecordRoute: RecordRoute,
  SessionsRoute: SessionsRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StudyPacksRoute: StudyPacksRoute,
  TeacherRoute: TeacherRoute,
  YoutubeRoute: YoutubeRoute,
  ApiChatRoute: ApiChatRoute,
  ApiStudyKitRoute: ApiStudyKitRoute,
  ApiStudyPackRoute: ApiStudyPackRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiYoutubeRoute: ApiYoutubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
